import Head from "next/head";
import Link from "next/link";
import { AddClubButton } from "~/components/home/add-club-button";
import { Divider } from "~/components/divider";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";
import { slugify } from "~/utils/slugify";

export default function Home() {
  const { data: userClubs, status } = api.club.getAllForUser.useQuery();

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full max-w-2xl flex-col gap-4 px-10">
        <div className="pt-10">
          <AddClubButton />
        </div>
        {status === "success" && userClubs.length !== 0 && (
          <>
            <Divider label="or" />
            <div className="flex max-h-[60dvh] flex-col gap-4 overflow-y-scroll pb-10">
              {userClubs.map((club, i) => (
                <Link
                  key={i}
                  href={`/club/${slugify(club.name)}`}
                  className="h-14 w-full"
                >
                  <Button variant="accent" size="lg" className="h-14 w-full">
                    {club.name}
                  </Button>
                </Link>
              ))}
            </div>
          </>
        )}
      </div>
    </>
  );
}
