import { UserButton } from "@clerk/nextjs";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import Head from "next/head";
import { env } from "~/env.mjs";

export default function Home() {
  const { data } = useQuery({
    queryKey: ["getGuardians"],
    queryFn: () =>
      axios
        .get(
          `http://www.omdbapi.com/?i=tt3896198&apikey=${env.NEXT_PUBLIC_OMDB_KEY}`,
        )
        .then((res) => res.data)
        .catch((error) => console.log(error)),
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <UserButton />
          <div></div>
        </div>
      </main>
    </>
  );
}
