import Head from "next/head";
import Link from "next/link";
import { AddClubButton } from "~/components/add-club-button";
import { Divider } from "~/components/divider";
import { Button } from "~/components/ui/button";
import { slugify } from "~/utils/slugify";

export default function Home() {
  const userClubs = [
    { name: "Club 1" },
    { name: "Club 2" },
    { name: "Club 3" },
  ];
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid place-items-center pt-40">
        <div className="flex w-full max-w-2xl flex-col gap-4 px-10">
          <AddClubButton
            handleCreate={() => {
              return;
            }}
          />
          {userClubs.length !== 0 && (
            <>
              <Divider label="or" />
              {userClubs.map((club, i) => (
                <Link
                  key={i}
                  href={`/club/${slugify(club.name)}`}
                  className="h-14 w-full"
                >
                  <Button variant="accent" size="lg" className="h-14 w-full">
                    {club.name}
                  </Button>
                </Link>
              ))}
            </>
          )}
        </div>
      </div>
    </>
  );
}
